name: Android CI Example Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  SELECTEL_AUTH_TOKENS_URL: "https://cloud.api.selcloud.ru/identity/v3/auth/tokens"
  SELECTEL_MOBILE_FARM_API_URL: "https://api.selectel.ru/mobfarm/api"
  USERNAME: ${{ secrets.USER_NAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
  PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
  ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
  DEVICE_SERIAL: ${{ secrets.DEVICE_SERIAL }}

jobs:
  run-autotests:
    runs-on: ubuntu-latest
    container:
      image: thyrlian/android-sdk:10.0 # Prebuilt Android SDK Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl jq

      - name: Update Android SDK
        run: |
          sdkmanager --update
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools" "cmdline-tools;latest"

      - name: Obtain Authorization Token
        run: |
          response=$(curl -s -D - -X POST \
            --header 'Content-Type: application/json' \
            --data-raw '{
              "auth": {
                "identity": {
                  "methods": ["password"],
                  "password": {
                    "user": {
                      "name": "${{ env.USER_NAME }}",
                      "domain": { "name": "${{ env.ACCOUNT_NAME }}" },
                      "password": "${{ env.PASSWORD }}"
                    }
                  }
                },
                "scope": {
                  "project": {
                    "name": "${{ env.PROJECT_NAME }}",
                    "domain": { "name": "${{ env.ACCOUNT_NAME }}" }
                  }
                }
              }
            }' \
            $SELECTEL_AUTH_TOKENS_URL)
          token=$(echo "$response" | grep -i "^x-subject-token" | awk '{print $2}' | tr -d '\r')
          echo "X_AUTH_TOKEN=$token" >> .env

      - name: Generate ADB Key Pair
        run: |
          mkdir -p ~/.android
          adb keygen ~/.android/adbkey
          adb pubkey ~/.android/adbkey > ~/.android/adbkey.pub

      - name: Store ADB Key in Mobile Farm
        shell: bash
        run: |
          source .env
          # TODO: delete me
          echo $X_AUTH_TOKEN
          echo "test"
          adb_pub_key=$(cat ~/.android/adbkey.pub)
          curl --location "$SELECTEL_MOBILE_FARM_API_URL/v2/keys/adb" \
            --header "Content-Type: application/json" \
            --header "X-Auth-Token: $X_AUTH_TOKEN" \
            --data "$(jq -n --arg title "$GITHUB_RUN_ID" --arg pubKey "$adb_pub_key" \
              '{"title": $title, "publicKey": $pubKey}')" \
            > response.json
          fingerprint=$(cat response.json | jq -r '.publicKey.fingerprint')
          echo "FINGERPRINT=$fingerprint" >> $GITHUB_ENV

      - name: Assign Device
        run: |
          source .env
          curl --location --request POST "$SELECTEL_MOBILE_FARM_API_URL/v1/user/devices" \
            --header "Accept: application/json" \
            --header "X-Auth-Token: $X_AUTH_TOKEN" \
            --header "Content-Type: application/json" \
            --data '{"serial": "${{ env.DEVICE_SERIAL }}", "timeout": 300000}'

      - name: Start Remote ADB Connection
        run: |
          source .env
          curl --location --request POST "$SELECTEL_MOBILE_FARM_API_URL/v1/user/devices/${{ env.DEVICE_SERIAL }}/remoteConnect" \
            --header "Accept: application/json" \
            --header "X-Auth-Token: $X_AUTH_TOKEN" \
            --output response_body.txt
          remote_connect_url=$(cat response_body.txt | jq -r '.remoteConnectUrl // ""')
          echo "UDID=$remote_connect_url" >> $GITHUB_ENV

      - name: Connect to ADB
        run: |
          adb connect {{ env.UDID }}
          sleep 1
          adb devices

      - name: Run Tests
        run: ./gradlew connectedAndroidTest

      - name: Release Device
        run: |
          source .env
          curl --location --request DELETE "$SELECTEL_MOBILE_FARM_API_URL/v1/user/devices/${{ env.DEVICE_SERIAL }}" \
            --header "Accept: application/json" \
            --header "X-Auth-Token: $X_AUTH_TOKEN"

      - name: Remove ADB Key
        if: ${{ always() && env.FINGERPRINT != '' }}
        run: |
          curl --location --request DELETE "$SELECTEL_MOBILE_FARM_API_URL/v2/keys/adb/{{ env.FINGERPRINT }}" \
            --header "Accept: application/json" \
            --header "X-Auth-Token: $X_AUTH_TOKEN"
